name: ℹBackend Request
description: Request for backend support
title: "[INFO] <title>"
labels: ["Backend Request"]
projects:
  - "Development"
body:
  - type: textarea
    attributes:
      label: TLDR;
      description: A one liner explaining the request
    validations:
      required: true

  - type: textarea
    attributes:
      label: Details
      description: |
        Links? References? Anything that will give you more context about this knowledge bite

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
